name: "Update documentation"

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
    paths:
    - docs/**
    - hack/doc-site/**
    - .github/workflows/update-doc.yml

  pull_request:
    paths:
    - docs/**
    - hack/doc-site/**
    - .github/workflows/update-doc.yml

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '1'
          submodules: recursive
          sparse-checkout: |
            hack/
            docs/
      -
        name: Initialize theme
        env:
          RELEARN_VERSION: 9.0.3
        run: |
          cd hack/doc-site/hugo

          # Clone theme
          curl -sL -o relearn.tgz https://github.com/McShelby/hugo-theme-relearn/archive/refs/tags/"${RELEARN_VERSION}".tar.gz
          tar xf relearn.tgz
          rm -rf themes/hugo-relearn
          mv "hugo-theme-relearn-${RELEARN_VERSION}" hugo-relearn
          mv hugo-relearn themes/
      -
        name: Prepare config
        run: |
          cd hack/doc-site/hugo

          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "    Build time: ${BUILD_TIME}"

          # Generate dynamic config
          cat docsite.yaml.template \
            | sed "s|{{ BUILD_TIME }}|${BUILD_TIME}|g" \
            > docsite.yaml
      -
        name: Build site with Hugo
        uses: crazy-max/ghaction-hugo@d629f74d3e4a9da53050610da35a59863ab9b26c # v3.3.0
        with:
          version: v0.153.3  # <- pin the HUGO version, as they often break things
          extended: true
          args: >
            --config hugo.yaml,docsite.yaml
            --buildDrafts
            --cleanDestinationDir
            --minify
            --printPathWarnings
            --ignoreCache
            --noBuildLock
            --logLevel info
            --source ${{ github.workspace }}/hack/doc-site/hugo"
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: hack/doc-site/hugo/public

  deploy-doc:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build-doc
    outputs:
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      -
        name: Report URL
        run: |
          echo "::notice::Deployed doc site to ${{ steps.deployment.outputs.page_url }}"
